version: 2
jobs:
  test:
    machine:
      image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            python -m pytest tests/test_rsvpapp.py  

  build:
    machine:
      image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout 
      - run:
          name: build image
          command: |
            docker build -t $DOCKERHUB_USERNAME/rsvpapp:$CIRCLE_SHA1 .
  push:
    machine:
      image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout 
      - run:
          name: Push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/rsvpapp:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/rsvpapp:$CIRCLE_SHA1    

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          context: DOCKERHUB
          filters:
            branches:
              only: dev        
      - build:
          context: DOCKERHUB 
          requires:
            - test
          filters:
            branches:
              only: dev
      - push:
          context: DOCKERHUB
          requires:
            - build
          filters:
            branches:
              only: dev
